# Generated by Django 2.2 on 2020-12-22 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201008_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.BigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)], verbose_name='phone_number'),
        ),
    ]
