# Generated by Django 3.2 on 2021-07-10 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unique_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Area', models.CharField(blank=True, max_length=200, null=True)),
                ('shop_photo1', models.ImageField(upload_to='Malls/')),
                ('shop_photo2', models.ImageField(upload_to='Malls/')),
                ('shop_photo3', models.ImageField(blank=True, null=True, upload_to='Malls/')),
                ('shop_photo4', models.ImageField(blank=True, null=True, upload_to='Malls/')),
                ('shop_photo5', models.ImageField(blank=True, null=True, upload_to='Malls/')),
                ('shop_photo6', models.ImageField(blank=True, null=True, upload_to='Malls/')),
                ('shop_photo7', models.ImageField(blank=True, null=True, upload_to='Malls/')),
                ('shop_photo8', models.ImageField(blank=True, null=True, upload_to='Malls/')),
                ('shop_photo9', models.ImageField(blank=True, null=True, upload_to='Malls/')),
                ('shop_photo10', models.ImageField(blank=True, null=True, upload_to='Malls/')),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Andaman and Nicobar', 'Andaman and Nicobar'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Chandigarh', 'Chandigarh'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram\t'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Puducherry', 'Puducherry'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Area', models.CharField(blank=True, max_length=100, null=True)),
                ('unique_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('shop_photo1', models.ImageField(upload_to='Markets/')),
                ('shop_photo2', models.ImageField(upload_to='Markets/')),
                ('shop_photo3', models.ImageField(blank=True, null=True, upload_to='Markets/')),
                ('shop_photo4', models.ImageField(blank=True, null=True, upload_to='Markets/')),
                ('shop_photo5', models.ImageField(blank=True, null=True, upload_to='Markets/')),
                ('shop_photo6', models.ImageField(blank=True, null=True, upload_to='Markets/')),
                ('shop_photo7', models.ImageField(blank=True, null=True, upload_to='Markets/')),
                ('shop_photo8', models.ImageField(blank=True, null=True, upload_to='Markets/')),
                ('shop_photo9', models.ImageField(blank=True, null=True, upload_to='Markets/')),
                ('shop_photo10', models.ImageField(blank=True, null=True, upload_to='Markets/')),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Andaman and Nicobar', 'Andaman and Nicobar'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Chandigarh', 'Chandigarh'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram\t'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Puducherry', 'Puducherry'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], max_length=100)),
                ('malls', models.ManyToManyField(to='Seller.Mall')),
            ],
        ),
        migrations.CreateModel(
            name='Pincodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, choices=[('Andaman and Nicobar', 'Andaman and Nicobar'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Chandigarh', 'Chandigarh'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram\t'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Puducherry', 'Puducherry'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name_of_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('photo_of_owner', models.ImageField(blank=True, null=True, upload_to='sellers/')),
                ('email_of_owner', models.EmailField(blank=True, max_length=254, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='sellers/')),
                ('cancel_cheque', models.ImageField(blank=True, null=True, upload_to='sellers/')),
                ('bank_account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('IFSC_code', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_number', models.BigIntegerField(blank=True, null=True)),
                ('Account_type', models.CharField(blank=True, choices=[('Saving', 'Saving'), ('Current', 'Current')], max_length=100, null=True)),
                ('mobile_number', models.BigIntegerField(blank=True, null=True)),
                ('alternate_number', models.BigIntegerField(blank=True, null=True)),
                ('shop_name', models.CharField(blank=True, max_length=100, null=True)),
                ('shop_photo1', models.ImageField(blank=True, null=True, upload_to='Shops/')),
                ('shop_photo2', models.ImageField(blank=True, null=True, upload_to='Shops/')),
                ('shop_photo3', models.ImageField(blank=True, null=True, upload_to='Shops/')),
                ('shop_photo4', models.ImageField(blank=True, null=True, upload_to='Shops/')),
                ('shop_photo5', models.ImageField(blank=True, null=True, upload_to='Shops/')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('Area', models.CharField(blank=True, max_length=100, null=True)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, choices=[('Andaman and Nicobar', 'Andaman and Nicobar'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Chandigarh', 'Chandigarh'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram\t'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Puducherry', 'Puducherry'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], max_length=100, null=True)),
                ('Order_history', models.ManyToManyField(blank=True, to='Base.Order')),
                ('mall_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Seller.mall')),
                ('market_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Seller.market')),
                ('products', models.ManyToManyField(blank=True, to='Base.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='market',
            name='shops',
            field=models.ManyToManyField(to='Seller.SellerProfile'),
        ),
        migrations.AddField(
            model_name='mall',
            name='shops',
            field=models.ManyToManyField(to='Seller.SellerProfile'),
        ),
    ]
