# Generated by Django 3.2 on 2021-07-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_delete_pincodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='Earning',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='sales',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
