# Generated by Django 3.2 on 2021-07-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0003_auto_20210719_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='Earning',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
