# Generated by Django 3.2 on 2021-07-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_order_item_order_to'),
        ('Seller', '0004_alter_sellerprofile_earning'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='My_orders',
            field=models.ManyToManyField(blank=True, to='Base.Order_Item'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='Order_history',
            field=models.ManyToManyField(blank=True, related_name='Order_history', to='Base.Order_Item'),
        ),
    ]
