# Generated by Django 3.2 on 2021-07-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_order_item_order_to'),
        ('Seller', '0005_auto_20210720_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='My_orders',
            field=models.ManyToManyField(blank=True, related_name='MO', to='Base.Order_Item'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='Order_history',
            field=models.ManyToManyField(blank=True, related_name='OH', to='Base.Order_Item'),
        ),
    ]
