# Generated by Django 3.2 on 2021-07-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0006_auto_20210722_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mall',
            name='shops',
            field=models.ManyToManyField(blank=True, to='Seller.SellerProfile'),
        ),
        migrations.AlterField(
            model_name='market',
            name='malls',
            field=models.ManyToManyField(blank=True, to='Seller.Mall'),
        ),
        migrations.AlterField(
            model_name='market',
            name='shops',
            field=models.ManyToManyField(blank=True, to='Seller.SellerProfile'),
        ),
    ]
