# Generated by Django 3.2 on 2021-07-24 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0007_auto_20210723_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerprofile',
            old_name='shop_name',
            new_name='name',
        ),
    ]
