# Generated by Django 3.2 on 2021-07-10 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='Seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Seller.sellerprofile'),
        ),
        migrations.AddField(
            model_name='product',
            name='UID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Seller.sellerprofile'),
        ),
    ]
