# Generated by Django 3.2 on 2021-07-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_auto_20210710_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
    ]
