# Generated by Django 3.2 on 2021-07-19 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_remove_product_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='Seller',
        ),
    ]
