# Generated by Django 3.2 on 2021-07-19 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_remove_order_item_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='order_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Base.order'),
        ),
    ]
