# Generated by Django 3.2 on 2021-07-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0007_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Name',
            field=models.TextField(),
        ),
    ]
