from django_elasticsearch_dsl import Document,Index,fields
from elasticsearch_dsl import analyzer,normalizer
from .models import Product
from Seller.models import Mall,Market,SellerProfile
products = Index('products')


# search keywords in every product
# warranty
# not found my product listed

@products.doc_type
class Products_Document(Document):

    class Django:
        model = Product

        fields =[
            'Name',
            'description',
            'main_category',
            'sub_category',
            'sub_sub_category',
            'sub_sub_sub_category',
            'Brand',
            'slug',
            'discount_price',
            'color',
            'overall_rating',
            # T shirt
            'Fit',
            'Pattern',
            'Neck_type',
            'Sleeve_type',
            'Theme' ,
            'Fabric' ,
            'occasion',
            'Collar',
            'type',
            'Distress',
            'Fade',
            'Waist_rise',
            'heel_height',
            'Length',
            'Closure',
            'Sleeve_style',
            'usage',
            'Hooded',
            'Ornamentation',
            'Styling',
            'Suitable_for',
            'Applied_for',
            'Hair_type',
            'Pack_of',
            'Washable',
            'Water_resistance',
            'Rise',
            'Straps',
            'Wire_support',
            'Padding',
            'Seam',
            'Coverage',
            'Back_style',
            'Dial_color',
            'Features',
            'Dial_shape',
            'Strap_material',
            'Number_of_compartments',
            'Material',
            'Bag_size',
            'wheels',
            'body_type',
            'capacity',
            'card_slot',
            'Strap_color',
            'Compatible_OS',
            'Display_type',
            'Gemstones',
            'Gender',
            'Blade_material',
            'Battery_run_time',
            'Body_material',
            'Plate_coating',
            'Dupatta_included',
            'Number_of_cores',
            'Wattage',
            'Collection',
            'Ring_size',
            'Dress_length',
            'Length_type',
            'Saree_type',
            'Saree_style',
            'Saree_length',
            'Blouse_included',
            'Saree_Fall_length',
            'Saree_Fall_width',
            'Rechargeable',
            'Battery_operated',
            'Thermoware',
            'Character',
            'Age_group',
            'Pot_included',
            'Bonsai',
            'Outer_material',
            'Towel_type',
            'Reversible',
            'width',
            'Microwave_safe',
            'Shape',
            'Showpiece_type',
            'No_of_prongs',
            'Quantity',
            'adjustable',
            'Fragrance',
            'Form',
            'Light_used',
            'Mount_type',
            'Bulb_included',
            'Dimmable',
            'Foldable',
            'Adjustable_height',
            'Mouse_tray',
            'Height',
            'Design',
            'Storage_included',
            'Separated',
            'Weight',
            'Heart_rate_sensor',
            'Diameter',
            'Contains_pump',
            'Thickness',
            'Grip',
            'Playing_level',
            'Strung_type',
            'Cover_type',
            'Grip_size',
            'Head_size',
            'Speed',
            'Willow_type',
            'Bat_grade',
            'Cover',
            'Visor',
            'Bails_included',
            'Fill_type',
            'Tyre_size',
            'Gear_type',
            'Rear_brake',
            'Front_brake',
            'Playback_mode',
            'Accessory_holder',
            'Rod_power',
            'Rod_type',
            'Handle_material',
            'Construction',
            'Rod_action',
            'Drag_type',
            'Container_type',
            'Edge_type',
            'Sheath',
            'Coated',
            'Finish',
            'Attachment_type',
            'Auto_locking',
            'Tray_included',
            'Magnetic',
            'Diary_type',
            'Steam_burst',
            'Spray',
            'Power_consumption',
            'Rated_pressure',
            'Star_rating',
            'Filter_type',
            'Auto_revolving_heater',
            'Number_of_stitches',
            'Number_of_blades',
            'Load_type',
            'Number_of_ways',
            'Wired_or_wireless',
            'Energy_ratings',
            'Ideal_for',
            'Technology',
            'Condenser_coil',
            'Defrosting_type',
            'Year',
            'Star',
            'Bee_rating',
            'Washing_system',
            'Control',
            'Power',
            'Cups',
            'Ductless',
            'Auto_clean',
            'Number_of_eggs',
            'Number_of_slices',
            'Screen_size',
            'Operating_system',
            'Hard_disk_capacity',
            'Storage_type',
            'Processor',
            'Processor_brand',
            'Processor_gen',
            'RAM_type',
            'RAM',
            'Graphics',
            'Graphics_name',
            'Graphics_processor_series',
            'Graphics_memory_type',
            'Touch_screen',
            'Interface',
            'Water_proof',
            'Operation_type',
            'Number_of_cells',
            'Compatible_laptop_size',
            'Ergonomic',
            'Illuminated_keys',
            'Shock_resistance',
            'Number_of_Ethernet_ports',
            'Wireless_speed',
            'Transfer_speed',
            'Voice_support',
            'Memory_capacity',
            'Max_wireless_transmission_rate',
            'Frequency_band',
            'Compatibility',
            'Frequency',
            'Number_of_USB_ports',
            'Antennae',
            'GST_invoice',
            'Offers',
            'Printer_type',
            'Scanner_type',
            'Printer_output',
            'Refilling_type',
            'Function',
            'Portable',
            'Device_chipset',
            'Lamp_life',
            'Brightness',
            'Edition',
            'Architecture',
            'Board',
            'Class',
            'Subject',
            'Validity',
            'Screen_resolution',
            'Screen_form_factor',
            'Inbuilt_speaker',
            'Panel_type',
            'Connectivity',
            'Response_time',
            'Fan_diameter',
            'Max_fan_speed',
            'Number_of_satacables',
            'Power_output',
            'Processor_speed',
            'Data_rate',
            'Device',
            'Chipset',
            'Clock_speed',
            'Number_of_HDMI_ports',
            'Configuration',
            'Smart_tv',
            'Screen_type',
            'Curve_tv',
            'Internal_storage',
            'Battery_capacity',
            'Network_type',
            'SIM_type',
            'Primary_camera',
            'Secondary_camera',
            'Operating_system_name',
            'Speciality',
            'Voice_calling',
            'Battery_type',
            'Syncing_method',
            'Wireless_standard',
            'Indicator',
            'Compatible_mobile',
            'Extension',
            'Movement',
            'Fixture_type',
            'Installation_type',
            'Sweep_diameter',
            'Phase',
            'Number_of_poles',
            'Flammable',
            'Sensor_type',
            'Effective_pixels',
            'Maximum_load_capacity',
            'Prime_Zoom',
            'Focal_length',
            'Lens_type',
            'Max_aperture',
            'Lens_mount',
            'Max_magnification',
            'Mount_tracking',
            'Placement_type',
            'Male_thread_diameter',
            'Female_thread_diameter',
            'Vehicle_brand',
            'Vehicle_model',
            'Number_of_indicator_lamps',
            'Tachometer',
            'Armours',
            'Platform',
            'PEGI_rating',
            'ESRB_rating',
            'Game_modes',
            'Temple_material',
            'Lens_type_supported',
            'Temple_color',
        ]


SellerProfile_index = Index('seller_profiles')
@SellerProfile_index.doc_type
class SellerProfile_Document(Document):

    class Django:
        model = SellerProfile

        fields =['name',
                 'unique_id',
                 'Area',
                 'district',
                 'state',
        ]

Mall_index = Index('malls')
@Mall_index.doc_type
class Mall_Document(Document):
    class Django:
        model = Mall

        fields = [
            'name',
            'Area',
            'unique_id',
            'district',
            'state',
        ]


Marketplace_index = Index('marketplaces')
@Marketplace_index.doc_type
class Market_Document(Document):
    class Django:
        model = Market

        fields = [
        'name',
        'Area',
        'unique_id',
        'district',
        'state',
        ]